# IMU 84-Feature MLP Trainer with Weight Export

This notebook:
1. Loads a CSV file with 84 features + label column.
2. Trains an MLP (**84 → 64 → 32 → 8**) using Keras/TensorFlow.
3. **Exports trained weights as numpy arrays** for deployment.

> **How to use**: Update `CSV_PATH` in the cell below to point to your features CSV file.


In [103]:
# Install dependencies if needed
!pip install pandas numpy scikit-learn tensorflow


In [122]:
from pathlib import Path
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
import collections
from google.colab import drive

# Now mount cleanly
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [105]:
# === Configure your paths here ===
# Set the path to your input CSV file with features
CSV_NAME = "N-13112025"
CSV_PATH = Path(f"/content/drive/My Drive/cg4002/test/2-imu-model/{CSV_NAME}.csv")  # <-- CHANGE THIS to your CSV file

# Output directory for weights
OUT_DIR = CSV_PATH.parent / CSV_NAME
OUT_DIR.mkdir(parents=True, exist_ok=True)
WEIGHTS_DIR = OUT_DIR / "weights_npy"
os.makedirs(WEIGHTS_DIR, exist_ok=True)

print("Input CSV:", CSV_PATH)
print("Weights will be saved to:", WEIGHTS_DIR)


Input CSV: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025.csv
Weights will be saved to: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025/weights_npy


In [106]:
# Load the feature dataset
# assert CSV_PATH.exists(), f"Feature CSV not found at {CSV_PATH}"
print(f"Checking for file at: {CSV_PATH.resolve()}")
data = pd.read_csv(CSV_PATH)
print("Loaded:", CSV_PATH, data.shape)
print("\nFirst few rows:")
display(data.head())

Checking for file at: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025.csv
Loaded: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025.csv (853, 87)

First few rows:


filename             file_key  label  Imu0_acc_x_mean  \
0  20251113_153812_244.csv  20251113_153812_244      1       976.300000   
1  20251113_153816_669.csv  20251113_153816_669      1      1004.558442   
2  20251113_153821_079.csv  20251113_153821_079      1       910.808219   
3  20251113_153825_370.csv  20251113_153825_370      1       647.697368   
4  20251113_153828_664.csv  20251113_153828_664      1       995.232877   

   Imu0_acc_x_std  Imu0_acc_x_rms  Imu0_acc_x_max  Imu0_acc_x_median  \
0       11.834695      976.371727          1007.0              976.0   
1      131.123367     1013.079957          1419.0              998.0   
2      418.717862     1002.445141          1999.0              975.0   
3      485.455701      809.431355          1601.0              690.5   
4       92.651582      999.536290          1554.0              976.0   

   Imu0_acc_y_mean  Imu0_acc_y_std  ...  Imu1_accmag_median  \
0      -149.425000       15.032278  ...          990.115123   
1      -150.623377      150.847652  ...         1024.266079   
2      -372.794521      242.219925  ...          994.831644   
3      -625.394737      448.357267  ...         1014.319262   
4      -251.506849      122.017978  ...         1002.047404   

   Imu1_gyromag_mean  Imu1_gyromag_std  Imu1_gyromag_rms  Imu1_gyromag_max  \
0         442.839776        230.230092        499.112174        991.901709   
1        5043.344659       3881.799927       6364.251411      23540.388463   
2        8505.875512      10870.267882      13802.631708      35374.937272   
3       15168.832612      10124.642108      18237.375377      33342.891731   
4        3316.890953       6742.968441       7514.611699      37571.290662   

   Imu1_gyromag_median  corr_acc_W_F  corr_gyr_W_F  ratio_acc_rms_F_over_W  \
0           410.562369      0.879205      0.882138                0.969648   
1          4657.864854      0.710514      0.737451                1.013890   
2          3540.184317      0.885852      0.979366                1.114996   
3         12460.015954      0.889853      0.970583                1.168348   
4          1622.239193      0.963154      0.991274                1.011341   

   ratio_gyr_rms_F_over_W  
0                1.157528  
1                1.254871  
2                1.103145  
3                1.035810  
4                1.237419  

[5 rows x 87 columns]

In [107]:
# Encode labels and prepare data
# Compress labels into contiguous IDs [0..K-1] for the model
unique_raw = np.sort(data['label'].unique())

# Optional: Define classes to exclude
classes_to_exclude = [] # Add the raw label values you want to exclude, e.g., [0, 7]

# Filter out excluded classes
if classes_to_exclude:
    print(f"Excluding classes: {classes_to_exclude}")
    data = data[~data['label'].isin(classes_to_exclude)].copy()
    unique_raw = np.sort(data['label'].unique())


raw_to_idx = {raw:i for i, raw in enumerate(sorted(unique_raw))}
idx_to_raw = {i:raw for raw,i in raw_to_idx.items()}

# Prepare features and labels
# Drop 'label', 'file_key' and 'file_name' if present
cols_to_drop = ['label']
if 'filename' in data.columns:
    cols_to_drop.append('filename')

if 'file_key' in data.columns:
    cols_to_drop.append('file_key')

X = data.drop(columns=cols_to_drop).values.astype(np.float32)
y_raw = data['label'].values.astype(int)
y = np.array([raw_to_idx[v] for v in y_raw], dtype=np.int64)

num_classes = len(np.unique(y))
print("Classes (raw→idx):", raw_to_idx)
print("num_classes:", num_classes)
print("Feature shape:", X.shape)

# Train/test split
X_train, X_test, y_train, y_test, y_raw_train, y_raw_test = train_test_split(
    X, y, y_raw, test_size=0.2, stratify=y, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s  = scaler.transform(X_test)

print(f"\nTrain: {X_train_s.shape}, Test: {X_test_s.shape}")

Classes (raw→idx): {np.int64(0): 0, np.int64(1): 1, np.int64(2): 2, np.int64(3): 3, np.int64(4): 4, np.int64(5): 5, np.int64(6): 6, np.int64(7): 7}
num_classes: 8
Feature shape: (853, 84)

Train: (682, 84), Test: (171, 84)


In [108]:
LABEL_MAP = {
"NONE": 0,
"SLIDE_LEFT": 1,
"SLIDE_RIGHT": 2,
"WRIST_TURN_CLOCKWISE": 3,
"WRIST_TURN_ANTI_CLOCKWISE": 4,
"SLIDE_UP": 5,
"SLIDE_DOWN": 6,
"GRASP": 7
}

In [109]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow.keras as keras
from tensorflow.keras import layers
import tensorflow as tf

# Build MLP model
input_dim = X_train_s.shape[1]
inputs = keras.Input(shape=(input_dim,), name="features", dtype='float32')
x = layers.Dense(64, activation="relu", name="dense_64", dtype='float32')(inputs)
x = layers.Dense(32, activation="relu", name="dense_32", dtype='float32')(x)
logits = layers.Dense(num_classes, activation=None, name="logits", dtype='float32')(x)

model = keras.Model(inputs=inputs, outputs=logits, name="imu_mlp_84_64_32")
model.summary()


Model: "imu_mlp_84_64_32"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ features (InputLayer)           │ (None, 84)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_64 (Dense)                │ (None, 64)             │         5,440 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ logits (Dense)                  │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,784 (30.41 KB)

 Trainable params: 7,784 (30.41 KB)

 Non-trainable params: 0 (0.00 B)

In [110]:
# Compile and train
model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[keras.metrics.SparseCategoricalAccuracy(name="acc")]
)

callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_acc", mode="max", patience=100, restore_best_weights=True)
]

history = model.fit(
    X_train_s, y_train,
    validation_split=0.1,
    epochs=200,
    batch_size=64,
    callbacks=callbacks,
    verbose=1
)


Epoch 1/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - acc: 0.1366 - loss: 2.0250 - val_acc: 0.3043 - val_loss: 1.6937
Epoch 2/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.2973 - loss: 1.7458 - val_acc: 0.4493 - val_loss: 1.5342
Epoch 3/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.4907 - loss: 1.6050 - val_acc: 0.5652 - val_loss: 1.4202
Epoch 4/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.6089 - loss: 1.3958 - val_acc: 0.5652 - val_loss: 1.3337
Epoch 5/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6590 - loss: 1.2673 - val_acc: 0.5652 - val_loss: 1.2565
Epoch 6/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - acc: 0.7461 - loss: 1.1424 - val_acc: 0.6377 - val_loss: 1.2067
Epoch 7/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7750 - loss: 0.9980 - val_acc: 0.6377 - val_loss: 1.1541
Epoch 8/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.7849 - loss: 0.9076 - val_acc: 0.7391 - val_loss: 1.1015
Epoch 9/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - ac

In [117]:
# Evaluate on test set
test_logits = model.predict(X_test_s, verbose=0)
test_pred = np.argmax(test_logits, axis=1)

test_acc = np.mean(test_pred == y_test)
print(f"Test Accuracy: {test_acc:.4f}")

# Confusion matrix
cm = confusion_matrix(y_test, test_pred, labels=range(num_classes))
print("\nConfusion matrix (idx space):\n", cm)

print("\nClassification report:")
print(classification_report(y_test, test_pred, digits=4))

# Label counts
print("\nData points per label (raw codes):")
cnt = collections.Counter(y_raw)
print(cnt)

Test Accuracy: 0.8655

Confusion matrix (idx space):
 [[18  0  0  1  0  2  1  0]
 [ 0 16  0  1  0  0  3  0]
 [ 0  0 24  0  0  0  1  0]
 [ 0  0  0 21  0  0  0  0]
 [ 0  0  0  1 20  1  0  0]
 [ 0  3  0  5  0 13  0  0]
 [ 0  0  1  0  0  0 19  0]
 [ 0  0  0  2  1  0  0 17]]

Classification report:
              precision    recall  f1-score   support

           0     1.0000    0.8182    0.9000        22
           1     0.8421    0.8000    0.8205        20
           2     0.9600    0.9600    0.9600        25
           3     0.6774    1.0000    0.8077        21
           4     0.9524    0.9091    0.9302        22
           5     0.8125    0.6190    0.7027        21
           6     0.7917    0.9500    0.8636        20
           7     1.0000    0.8500    0.9189        20

    accuracy                         0.8655       171
   macro avg     0.8795    0.8633    0.8630       171
weighted avg     0.8826    0.8655    0.8658       171


Data points per label (raw codes):
Counter({np.int64(

In [118]:
# Export trained weights as NumPy arrays
from tensorflow.keras.layers import Dense

def save_dense(layer, prefix):
    W, b = layer.get_weights()
    np.save(os.path.join(WEIGHTS_DIR, f"{prefix}_W.npy"), W.astype(np.float32))
    np.save(os.path.join(WEIGHTS_DIR, f"{prefix}_b.npy"), b.astype(np.float32))
    print(f"Saved {prefix}_W.npy {W.shape}, {prefix}_b.npy {b.shape}")

# Save all Dense layers
for lyr in model.layers:
    if isinstance(lyr, Dense):
        save_dense(lyr, lyr.name)

print("\nDone → Weights saved to:", os.path.abspath(WEIGHTS_DIR))


Saved dense_64_W.npy (84, 64), dense_64_b.npy (64,)
Saved dense_32_W.npy (64, 32), dense_32_b.npy (32,)
Saved logits_W.npy (32, 8), logits_b.npy (8,)

Done → Weights saved to: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025/weights_npy


In [119]:
# Save test cases for verification
X_test_10 = X_test_s[10:20]
y_test_10 = y_test[10:20]

test_logits_10 = model.predict(X_test_10, verbose=0)
test_pred_10 = np.argmax(test_logits_10, axis=1)

print(f"Test predictions (10 samples):\n{test_pred_10}")
test_acc = np.mean(test_pred_10 == y_test_10)
print(f"Test Accuracy (10 samples): {test_acc:.4f}")

# Save test I/O
io_npy_dir = os.path.join(OUT_DIR, "io_npy")
os.makedirs(io_npy_dir, exist_ok=True)

np.save(os.path.join(io_npy_dir, "test_x.npy"), X_test_10)
np.save(os.path.join(io_npy_dir, "test_y.npy"), test_logits_10)

print(f"\nSaved test_x.npy, test_y.npy to: {io_npy_dir}")


Test predictions (10 samples):
[6 4 7 0 7 3 3 2 3 2]
Test Accuracy (10 samples): 0.9000

Saved test_x.npy, test_y.npy to: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025/io_npy


In [ ]:
import numpy as np

# User provided input string
input_str = "-0.6238287853610518,-0.7198319874134484,-1.2024924794472678,-1.1586517084598364,-0.5606992365263722,-0.06855423085461675,-0.6510513636095118,-0.5798605219634851,-0.5380123697844454,-0.06843620513278877,1.172397503206463,-0.6684738298642866,0.4731044292333197,0.47312100250191047,1.0888030916150186,-0.018484584063625135,-0.715191217248631,-1.114485516934688,-0.8101473942427218,-0.043024814462656324,0.008480388443704126,-0.9140425787861426,-1.350940000065674,-0.9668651654773261,-0.03749415924110769,-0.02414041941287088,-0.7109821116568729,-1.111626666111934,-0.7214915276236258,-0.10056794101434843,-0.2402494754784003,-0.8630185087314682,-0.3105421307760723,-0.9906598464797365,-0.14062478292343578,-1.4804248572510157,-1.3962294566315092,-1.7162304188469855,-2.0938520154246407,-1.054084170223842,0.2677069872107624,-0.7507737414557626,-0.6169808383292128,-0.5849904635978734,0.31888854304902653,0.11404100050723492,-0.6465826790427728,-1.1091874950538527,-0.5722281993766543,0.1423237589286006,1.437824409067713,-0.7802306598280674,0.3811734137433785,0.1969917298961259,1.353543848207439,-0.07182643790219201,-0.810760570847598,-1.2334416332369822,-0.8904319483765271,-0.07974710146579271,-0.08837338768012354,-0.9537111071528112,-1.4629374642213926,-1.1445768718167986,-0.07556858425663045,-0.01427494612706697,-0.7310586216802164,-1.1185264032477307,-0.8290105844004619,0.02853662568373015,-0.3005060042792365,-0.9480945788318456,-0.4157561075807725,-1.1923119710752803,-0.10197756119565266,-1.5582843580338595,-1.4554200591715556,-1.7937135043441175,-2.1501510866658813,-1.104266325092868,-2.01161838126501,-2.85806664492955,-0.1696624513321804,-0.3444394863554028"

# Convert string to numpy array
input_features = np.array([float(x) for x in input_str.split(',')]).reshape(1, -1)

# Scale the input features using the pre-fitted scaler
# Ensure the scaler object is available from previous cells
scaled_input_features = scaler.transform(input_features)

# Make a prediction
predictions = model.predict(scaled_input_features, verbose=0)
predicted_label_idx = np.argmax(predictions, axis=1)[0]

# Map the predicted index back to the raw label
predicted_raw_label = idx_to_raw.get(predicted_label_idx, f"Unknown index: {predicted_label_idx}")

# Print the results
print(f"Input Feature Vector (first 5 values): {input_features[0,:5]}...")
print(f"Scaled Input Feature Vector (first 5 values): {scaled_input_features[0,:5]}...")
print(f"Raw Logit Predictions: {predictions[0]}")
print(f"Predicted Label Index: {predicted_label_idx}")
print(f"Predicted Raw Label: {predicted_raw_label}")

# Optional: Print the friendly label name using the LABEL_MAP
friendly_label_found = False
for name, idx in LABEL_MAP.items():
    if idx == predicted_raw_label:
        print(f"Predicted Friendly Label: {name}")
        friendly_label_found = True
        break
if not friendly_label_found:
    print("Could not find a friendly name for the predicted label in LABEL_MAP.")

Input Feature Vector (first 5 values): [-0.62382879 -0.71983199 -1.20249248 -1.15865171 -0.56069924]...
Scaled Input Feature Vector (first 5 values): [-0.40159394 -0.72734439 -1.54118388 -0.97185659 -0.34941475]...
Raw Logit Predictions: [ -1.358511 -31.11856  -11.57878  -35.939926   7.955253 -24.160004
  -4.472461  29.322483]
Predicted Label Index: 7
Predicted Raw Label: 7
Predicted Friendly Label: GRASP


In [120]:
import joblib
import os

# Save the scaler object to the OUT_DIR
joblib.dump(scaler, os.path.join(OUT_DIR, "scaler.pkl"))
print(f"Scaler saved to: {os.path.join(OUT_DIR, 'scaler.pkl')}")

Scaler saved to: /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025/scaler.pkl


In [ ]:
# Count trainable parameters
def count_trainable_params(keras_model: keras.Model) -> int:
    return int(np.sum([np.prod(v.shape) for v in keras_model.trainable_weights]))

print("Total trainable parameters:", count_trainable_params(model))


Total trainable parameters: 7784


# Task
The task is to load the previously saved weights and the scaler to reconstruct and test the MLP model. This involves:
1. Recreating the Keras MLP model architecture.
2. Loading the saved `.npy` weight and bias files into the corresponding layers of the reconstructed model.
3. Loading the `scaler.pkl` file using joblib.
4. Using the loaded model and scaler to make a prediction on a sample input from `X_test_10` (or a hardcoded feature vector) and display the predicted label and the corresponding friendly label.

## Reconstruct the MLP Model

### Subtask:
Define the same Keras MLP architecture (84 -> 64 -> 32 -> 8) as used for training, but without compiling or training.


**Reasoning**:
The subtask requires defining the Keras MLP model architecture with specific layer configurations. This code block will construct the model as specified in the instructions.



In [ ]:
import tensorflow.keras as keras
from tensorflow.keras import layers

# Define the input dimension
input_dim = 84
num_classes = 8 # Based on the previous notebook execution, 8 classes were identified.

# Create the Keras MLP model
inputs = keras.Input(shape=(input_dim,), name="features", dtype='float32')
x = layers.Dense(64, activation="relu", name="dense_64", dtype='float32')(inputs)
x = layers.Dense(32, activation="relu", name="dense_32", dtype='float32')(x)
logits = layers.Dense(num_classes, activation=None, name="logits", dtype='float32')(x)

reconstructed_model = keras.Model(inputs=inputs, outputs=logits, name="imu_mlp_84_64_32")
reconstructed_model.summary()

Model: "imu_mlp_84_64_32"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ features (InputLayer)           │ (None, 84)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_64 (Dense)                │ (None, 64)             │         5,440 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ logits (Dense)                  │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,784 (30.41 KB)

 Trainable params: 7,784 (30.41 KB)

 Non-trainable params: 0 (0.00 B)

**Reasoning**:
The next logical step is to load the previously saved weights and biases from the .npy files into the corresponding layers of the reconstructed Keras model. This will prepare the model for prediction.



In [ ]:
import os
import numpy as np
from pathlib import Path

# Re-define WEIGHTS_DIR and related paths
CSV_NAME = "7_and_null"
CSV_PATH = Path(f"/content/drive/My Drive/cg4002/test/2-imu-model/{CSV_NAME}.csv")
OUT_DIR = CSV_PATH.parent / CSV_NAME
OUT_DIR.mkdir(parents=True, exist_ok=True)
WEIGHTS_DIR = OUT_DIR / "weights_npy"
os.makedirs(WEIGHTS_DIR, exist_ok=True)

# Load weights into the reconstructed model
for lyr in reconstructed_model.layers:
    if isinstance(lyr, keras.layers.Dense):
        name = lyr.name
        weights_path = os.path.join(WEIGHTS_DIR, f"{name}_W.npy")
        bias_path = os.path.join(WEIGHTS_DIR, f"{name}_b.npy")

        if os.path.exists(weights_path) and os.path.exists(bias_path):
            W = np.load(weights_path)
            b = np.load(bias_path)
            lyr.set_weights([W, b])
            print(f"Loaded weights for layer: {name}")
        else:
            print(f"Warning: Weights or biases not found for layer: {name}")

print("All available weights loaded into reconstructed_model.")

Loaded weights for layer: dense_64
Loaded weights for layer: dense_32
Loaded weights for layer: logits
All available weights loaded into reconstructed_model.


**Reasoning**:
The next step is to load the previously saved scaler object, which is necessary to preprocess new input data before making predictions with the reconstructed model. The `joblib` library is used for this purpose.



In [ ]:
import joblib

# Assuming OUT_DIR is available from previous cells and correctly points to the directory
# where the scaler.pkl file was saved.
# If not, it would need to be re-defined as done with WEIGHTS_DIR.

scaler_path = os.path.join(OUT_DIR, "scaler.pkl")

if os.path.exists(scaler_path):
    scaler = joblib.load(scaler_path)
    print(f"Scaler loaded from: {scaler_path}")
else:
    print(f"Error: Scaler file not found at {scaler_path}")


Scaler loaded from: /content/drive/My Drive/cg4002/test/2-imu-model/7_and_null/scaler.pkl


## Make a Prediction with the Reconstructed Model and Scaler

### Subtask:
Use the loaded model and scaler to make a prediction on a sample input. This involves:
1. Preparing a sample input feature vector (e.g., `input_str` from the original notebook or `X_test_10`'s first entry).
2. Scaling the input feature vector using the loaded `scaler`.
3. Making a prediction with the `reconstructed_model`.
4. Mapping the predicted index back to its raw and friendly label using `idx_to_raw` and `LABEL_MAP` (which were defined previously).

**Reasoning**:
Now that the model and scaler are loaded, the next logical step is to use them to make a prediction on a sample input feature vector. This will demonstrate that the reconstruction was successful. I will use the `input_str` and re-define `LABEL_MAP` and `idx_to_raw` to ensure all necessary variables are available.



In [113]:
import numpy as np

# Re-define LABEL_MAP and idx_to_raw if not available from previous cells
LABEL_MAP = {
"NONE": 0,
"SLIDE_LEFT": 1,
"SLIDE_RIGHT": 2,
"WRIST_TURN_CLOCKWISE": 3,
"WRIST_TURN_ANTI_CLOCKWISE": 4,
"SLIDE_UP": 5,
"SLIDE_DOWN": 6,
"GRASP": 7
}

# Based on previous execution output:
# Classes (raw→idx): {np.int64(0): 0, np.int64(1): 1, np.int64(2): 2, np.int64(3): 3, np.int64(4): 4, np.int64(5): 5, np.int64(6): 6, np.int64(7): 7}
idx_to_raw = {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7}

# User provided input string from earlier in the notebook
input_str = "-0.6238287853610518,-0.7198319874134484,-1.2024924794472678,-1.1586517084598364,-0.5606992365263722,-0.06855423085461675,-0.6510513636095118,-0.5798605219634851,-0.5380123697844454,-0.06843620513278877,1.172397503206463,-0.6684738298642866,0.4731044292333197,0.47312100250191047,1.0888030916150186,-0.018484584063625135,-0.715191217248631,-1.114485516934688,-0.8101473942427218,-0.043024814462656324,0.008480388443704126,-0.9140425787861426,-1.350940000065674,-0.9668651654773261,-0.03749415924110769,-0.02414041941287088,-0.7109821116568729,-1.111626666111934,-0.7214915276236258,-0.10056794101434843,-0.2402494754784003,-0.8630185087314682,-0.3105421307760723,-0.9906598464797365,-0.14062478292343578,-1.4804248572510157,-1.3962294566315092,-1.7162304188469855,-2.0938520154246407,-1.054084170223842,0.2677069872107624,-0.7507737414557626,-0.6169808383292128,-0.5849904635978734,0.31888854304902653,0.11404100050723492,-0.6465826790427728,-1.1091874950538527,-0.5722281993766543,0.1423237589286006,1.437824409067713,-0.7802306598280674,0.3811734137433785,0.1969917298961259,1.353543848207439,-0.07182643790219201,-0.810760570847598,-1.2334416332369822,-0.8904319483765271,-0.07974710146579271,-0.08837338768012354,-0.9537111071528112,-1.4629374642213926,-1.1445768718167986,-0.07556858425663045,-0.01427494612706697,-0.7310586216802164,-1.1185264032477307,-0.8290105844004619,0.02853662568373015,-0.3005060042792365,-0.9480945788318456,-0.4157561075807725,-1.1923119710752803,-0.10197756119565266,-1.5582843580338595,-1.4554200591715556,-1.7937135043441175,-2.1501510866658813,-1.104266325092868,-2.01161838126501,-2.85806664492955,-0.1696624513321804,-0.3444394863554028"

# Convert string to numpy array
input_features = np.array([float(x) for x in input_str.split(',')]).reshape(1, -1)

# Scale the input features using the loaded scaler
scaled_input_features = scaler.transform(input_features)

# Make a prediction with the reconstructed model
predictions = model.predict(scaled_input_features, verbose=0)
predicted_label_idx = np.argmax(predictions, axis=1)[0]

# Map the predicted index back to the raw label
predicted_raw_label = idx_to_raw.get(predicted_label_idx, f"Unknown index: {predicted_label_idx}")

# Print the results
print(f"Input Feature Vector (first 5 values): {input_features[0,:5]}...")
print(f"Scaled Input Feature Vector (first 5 values): {scaled_input_features[0,:83]}...")
print(f"Raw Logit Predictions: {predictions[0]}")
print(f"Predicted Label Index: {predicted_label_idx}")
print(f"Predicted Raw Label: {predicted_raw_label}")

# Optional: Print the friendly label name using the LABEL_MAP
friendly_label_found = False
for name, idx in LABEL_MAP.items():
    if idx == predicted_raw_label:
        print(f"Predicted Friendly Label: {name}")
        friendly_label_found = True
        break
if not friendly_label_found:
    print("Could not find a friendly name for the predicted label in LABEL_MAP.")


Input Feature Vector (first 5 values): [-0.62382879 -0.71983199 -1.20249248 -1.15865171 -0.56069924]...
Scaled Input Feature Vector (first 5 values): [-1.75332797e+00 -5.18643767e-01 -3.78312265e+00 -2.00866314e+00
 -2.26970410e+00  6.90197247e-01 -5.74225318e-01 -1.45731014e+00
 -4.30962796e-01  9.99314272e-01 -4.67109640e-01 -6.35633020e-01
 -1.41146498e+00 -1.14271078e+00 -6.23059363e-01  2.02796474e-02
 -8.44150822e-01 -1.34127878e+00 -1.03236113e+00 -8.38709202e-02
  1.65841085e-01 -7.80414838e-01 -1.28629671e+00 -8.63662770e-01
  1.78704311e-01  2.97780328e-02 -7.29810514e-01 -1.25562094e+00
 -9.13878047e-01 -4.14268695e-02 -3.77062702e+00 -9.73838173e-01
 -3.46018846e+00 -2.89462467e+00 -4.45362051e+00 -1.31760149e+00
 -1.36552412e+00 -1.57193608e+00 -1.95078133e+00 -9.66843291e-01
 -1.03515542e+00 -6.79577858e-01 -2.53965512e+00 -1.77701924e+00
 -9.68036374e-01 -4.49191543e-02 -5.81592465e-01 -1.03053739e+00
 -8.87735888e-01 -4.42009973e-02  8.40359056e-01 -7.12860035e-01
 -2.1

In [123]:
import numpy as np
import pandas as pd

# Re-define LABEL_MAP and idx_to_raw if not available from previous cells
LABEL_MAP = {
    "NONE": 0,
    "SLIDE_LEFT": 1,
    "SLIDE_RIGHT": 2,
    "WRIST_TURN_CLOCKWISE": 3,
    "WRIST_TURN_ANTI_CLOCKWISE": 4,
    "SLIDE_UP": 5,
    "SLIDE_DOWN": 6,
    "GRASP": 7
}

# Based on previous execution output:
# Classes (raw→idx): {np.int64(0): 0, np.int64(1): 1, np.int64(2): 2, np.int64(3): 3, np.int64(4): 4, np.int64(5): 5, np.int64(6): 6, np.int64(7): 7}
idx_to_raw = {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7}

# Read the CSV file
csv_path = os.path.join(OUT_DIR, "new-onx-13112025.csv")# Update this path as needed
df = pd.read_csv(csv_path)

# Extract feature columns (exclude filename and file_key)
feature_columns = df.columns  # Skip first 2 columns (filename, file_key)
input_features = df[feature_columns].values

# Scale the input features using the loaded scaler
scaled_input_features = scaler.transform(input_features)

# Make predictions with the reconstructed model
predictions = model.predict(scaled_input_features, verbose=0)
predicted_label_indices = np.argmax(predictions, axis=1)

# Print results for each row
print("="*80)
print(f"Processing {len(df)} samples from {csv_path}")
print("="*80)

for i in range(len(df)):
    predicted_label_idx = predicted_label_indices[i]
    predicted_raw_label = idx_to_raw.get(predicted_label_idx, f"Unknown index: {predicted_label_idx}")

    # Find friendly label name
    friendly_label = "Unknown"
    for name, idx in LABEL_MAP.items():
        if idx == predicted_raw_label:
            friendly_label = name
            break

    # print(f"\nSample {i+1}: {df['filename'].iloc[i]}")
    print(f"  Input Feature Vector (first 5 values): {input_features[i,:5]}...")
    print(f"  Raw Logit Predictions: {predictions[i]}")
    print(f"  Predicted Label Index: {predicted_label_idx}")
    print(f"  Predicted Raw Label: {predicted_raw_label}")
    print(f"  Predicted Friendly Label: {friendly_label}")

# Summary
print("\n" + "="*80)
print("SUMMARY")
print("="*80)
# for i, (filename, pred_idx) in enumerate(zip(df['filename'], predicted_label_indices)):
#     predicted_raw_label = idx_to_raw.get(pred_idx, f"Unknown")
#     friendly_label = "Unknown"
#     for name, idx in LABEL_MAP.items():
#         if idx == predicted_raw_label:
#             friendly_label = name
#             break
#     print(f"{filename}: {friendly_label}")

Processing 313 samples from /content/drive/My Drive/cg4002/test/2-imu-model/N-13112025/new-onx-13112025.csv
  Input Feature Vector (first 5 values): [ 1.12290308  1.03811069 -0.30493736 -0.7510378  -1.74618248]...
  Raw Logit Predictions: [ -6.5926585   -7.0649476  -10.963447     3.8551648    0.37398845
  -3.5061283   -2.9819903    8.870428  ]
  Predicted Label Index: 7
  Predicted Raw Label: 7
  Predicted Friendly Label: GRASP
  Input Feature Vector (first 5 values): [ 0.68269253  1.03807051 -0.30120621 -0.75255947 -1.75708495]...
  Raw Logit Predictions: [ -6.547601    -6.901404   -11.188501     3.8626366    0.10616523
  -3.6811192   -2.8135788    8.943063  ]
  Predicted Label Index: 7
  Predicted Raw Label: 7
  Predicted Friendly Label: GRASP
  Input Feature Vector (first 5 values): [ 0.68269253  1.05150504 -0.30120621 -0.74227063 -1.75671785]...
  Raw Logit Predictions: [ -6.5334353   -6.8540597  -11.2838745    3.8525589    0.04576403
  -3.736845    -2.7687578    9.029525  ]
  Pred

## Summary:

### Data Analysis Key Findings
*   The MLP model architecture (84 input features, followed by dense layers with 64 and 32 neurons, and an 8-neuron output layer) was successfully recreated.
*   Weights and biases for all Dense layers (`dense_64`, `dense_32`, `logits`) were loaded successfully from their respective `.npy` files.
*   The `scaler.pkl` file was successfully loaded using `joblib`.
*   A sample input feature vector was scaled using the loaded `scaler`. The reconstructed model then predicted the label index 7, which corresponds to the raw label 7 and the friendly label "GRASP".

### Insights or Next Steps
*   The successful reconstruction and prediction confirm that the saved model components (weights and scaler) are intact and functional, allowing for deployment or further testing.
*   The reconstructed model can now be integrated into an application for inference, enabling real-time classification of new data.
